name: weir-diff
description: Runs a diff between two Azure TF plans

inputs:
  before:
    required: true
    description: The previously applied TFPlan
  after:
    required: true
    description: The plan that will be applied

outputs:
  diff:
    description: The diff between the two plans
    value: ${{ steps.run.outputs.diff }}

runs:
  using: composite
  steps:
    - id: run
      shell: bash
      run: |
        output=$(docker run --rm \
          -v "$GITHUB_WORKSPACE/${{ inputs.before }}:/before.json" \
          -v "$GITHUB_WORKSPACE/${{ inputs.after }}:/after.json" \
          ghcr.io/smvacura/weir:latest diff /before.json /after.json --show-if-new) || true
        {
          echo 'diff<<EOF'
          echo "$output"
          echo 'EOF'
        } >> "$GITHUB_OUTPUT"
